apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mlflow-helm.fullname" . }}
  labels:
    {{- include "mlflow-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.server.autoscaling.enabled }}
  replicas: {{ .Values.server.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mlflow-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mlflow-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.server.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mlflow-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.server.securityContext | nindent 12 }}
          command:
          - "bash"
          - "-c"
          args:
          {{- include "mlflow.server.cmd" . | indent 12 }}
          # - "mlflow server --default-artifact-root ${ARTIFACT_STORE} --backend-store-uri postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_URL}:${DATABASE_PORT}/${DATABASE_NAME} --host 0.0.0.0"
          # mlflow server --default-artifact-root https://ds-k8s-d2.nonprod.bis.sie.sony.com/mlflow/api/2.0/mlflow-artifacts/artifacts/experiments
          # --backend-store-uri postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_URL}:${DATABASE_PORT}/${DATABASE_NAME}
          # --host 0.0.0.0 --serve-artifacts --artifacts-destination ${ARTIFACT_STORE}
          # --gunicorn-opts "--log-level debug"
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          env:
            {{- include "mlflow.env" . | indent 12 }}
      {{- with .Values.server.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.server.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
