{{- $fullName := include "mlflow-helm.fullname" . -}}
{{- if .Values.server.ingress.traefik.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
    {{- include "mlflow-helm.labels" . | nindent 4 }}
  {{- with .Values.server.ingress.traefik.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $fullName }}
  namespace: {{ .Values.server.ingress.traefik.namespace }}
spec:
  entryPoints: {{ .Values.server.ingress.traefik.entryPoints }}
  routes:
    {{- range .Values.server.ingress.traefik.routes }}
    - kind: {{ .kind }}
      match: {{ .match | quote }}
      services:
      {{- range .services }}
      - kind: {{ .kind }}
        namespace: {{ .namespace }}
        name: {{ $fullName }}
        port: {{ .port }}
      {{- end }}
    {{- end }}
  tls:
  {{- range .Values.server.ingress.traefik.tls }}
  - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
{{- end}}
